jwt:
  secret:
    key: sk1234567890123456789012345678901234567890123456789012345678901234

kakao:
  client.id: 6398d9af5ef725591eb15e058b0e36bb
  redirect.uri: http://localhost:8080/login/oauth2/code/kakao
  allim:
    uri: https://kapi.kakao.com/v2/api/talk/memo/default/send
  oauth:
    token.uri: https://kauth.kakao.com/oauth/authorize?
    user.uri: https://kapi.kakao.com/v2/user/me
    access.uri: https://kauth.kakao.com/oauth/token?
    profile.uri: https://kapi.kakao.com/v2/user/me
    logout.uri: https://kapi.kakao.com/v1/user/logout

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE

