spring:
  config:
    import: application-secret.yml

  h2:
    console:
      enabled: true

  sql:
    init:
      mode: always
      data-locations: classpath:sql/data.sql

  jpa:
    defer-datasource-initialization: true #Hibernate 초기화 후 data.sql 실행

jwt:
  expiration: 86400000 #24시간

logging:
  level:
    gift.authentication: debug

cors:
  path-patterns: "/**"
  origin-patterns: "http://localhost:3000"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"
  allow-credentials: true
  max-age: 1800
