insert into category(name, color, image_url, description) values('상품', 'red', 'https://st.kakaocdn.net/category1.jpg', '상품 카테고리입니다.')
insert into category(name, color, image_url, description) values('차량', 'red', 'https://st.kakaocdn.net/category1.jpg', '차량 카테고리입니다.')
insert into category(name, color, image_url, description) values('패션', 'blue', 'https://st.kakaocdn.net/category2.jpg', '패션 카테고리입니다.')
insert into category(name, color, image_url, description) values('뷰티', 'green', 'https://st.kakaocdn.net/category3.jpg', '뷰티 카테고리입니다.')

insert into product(name, price, image_url, category_id, created_at) values ('product1', 1000, 'https://picsum.photos/200/300', 1, NOW())
insert into product(name, price, image_url, category_id, created_at) values ('product2', 2000, 'https://picsum.photos/200/300', 2, NOW())
insert into product(name, price, image_url, category_id, created_at) values ('product3', 3000, 'https://picsum.photos/200/300', 3, NOW())
insert into product(name, price, image_url, category_id, created_at) values ('product4', 4000, 'https://picsum.photos/200/300', 4, NOW())
insert into product(name, price, image_url, category_id, created_at) values ('product5', 5000, 'https://picsum.photos/200/300', 1, NOW())
insert into product(name, price, image_url, category_id, created_at) values ('product6', 6000, 'https://picsum.photos/200/300', 2, NOW())
insert into product(name, price, image_url, category_id, created_at) values ('product7', 7000, 'https://picsum.photos/200/300', 3, NOW())
insert into product(name, price, image_url, category_id, created_at) values ('product8', 8000, 'https://picsum.photos/200/300', 4, NOW())
insert into product(name, price, image_url, category_id, created_at) values ('product9', 9000, 'https://picsum.photos/200/300', 1, NOW())

insert into users(password, email, name, social_Type) values ('yso3865', 'yso829612@gmail.com', 'user1', 'DEFAULT')

insert into wish(user_id, product_id, created_at) values(1, 1, NOW())
insert into wish(user_id, product_id, created_at) values(1, 2, NOW())
insert into wish(user_id, product_id, created_at) values(1, 3, NOW())
insert into wish(user_id, product_id, created_at) values(1, 4, NOW())

insert into options(name, quantity, product_id) values('option1', 100, 1)
insert into options(name, quantity, product_id) values('option2', 100, 2)
insert into options(name, quantity, product_id) values('option3', 100, 3)
insert into options(name, quantity, product_id) values('option4', 100, 4)
insert into options(name, quantity, product_id) values('option5', 100, 5)
insert into options(name, quantity, product_id) values('option6', 100, 6)
insert into options(name, quantity, product_id) values('option7', 100, 7)
insert into options(name, quantity, product_id) values('option8', 100, 8)
insert into options(name, quantity, product_id) values('option9', 100, 9)
