SET REFERENTIAL_INTEGRITY FALSE;
TRUNCATE TABLE wish RESTART IDENTITY;
TRUNCATE TABLE users RESTART IDENTITY;
TRUNCATE TABLE product RESTART IDENTITY;
TRUNCATE TABLE category RESTART IDENTITY;
SET REFERENTIAL_INTEGRITY TRUE;