SET REFERENTIAL_INTEGRITY FALSE;
TRUNCATE TABLE member RESTART IDENTITY;
TRUNCATE TABLE product RESTART IDENTITY;
TRUNCATE TABLE wishlist RESTART IDENTITY;
TRUNCATE TABLE Category RESTART IDENTITY;
TRUNCATE TABLE Options RESTART IDENTITY;
SET REFERENTIAL_INTEGRITY TRUE;
