= Gift Service API Document
:doctype: books
:icons: front
:toc: left
:toc-title: Gift Service API Document
:toclevels: 1
:source-highlighter:
:iconsdir: fas

// :operation-request-fields-title: 본문(Body)
// :operation-response-fields-title: 본문(Body)
// :operation-http-request-title: 본문(Body)
// :operation-http-response-title: 본문(Body)
// operation::category-add[snippets='request-fields','response-fields','http-request','http-response']
// You can refer to Section A in File 1 with this link: xref:product.adoc[Go to Section A in File 1].

== 회원가입
=== 기본정보
|===
|Method | URL |Authentication method

|POST
|/api/members/register
|NONE
|===
**설명**: 새로운 사용자가 회원가입을 위해 이메일과 비밀번호를 제출하여 계정을 생성합니다. 성공적으로 가입하면 액세스 토큰을 받게 됩니다.

=== 요청
operation::member-register[snippets='request-fields,request-body']
=== 응답
operation::member-register[snippets='response-fields,response-body']
=== 예제
operation::member-register[snippets='http-request,http-response']



== 카카오 로그인
=== 기본정보
|===
|Method | URL |Authentication method

|GET
|/oauth/kakao
|NONE
|===
**설명**: 기존 사용자가 카카오 로그인을 시도합니다. 성공적으로 로그인하면 액세스 토큰을 받게 됩니다.

위 URL로 GET 요청하시면 카카오 로그인 창으로 리다이렉트 됩니다. **카카오 로그인 성공시 토큰을 반환합니다.**

=== 요청
operation::kakaologin[snippets='request-body']
=== 응답
==== 카카오 로그인 성공시
operation::member-login[snippets='response-fields,response-body']

=== 예제

operation::kakaologin[snippets='http-request,http-response']
==== 카카오 로그인 성공시
operation::member-login[snippets='http-response']



== 상품 조회
=== 기본정보
|===
|Method | URL |Authentication method

|GET
|/api/products/{productId}
|NONE
|===
**설명**: 상품의 ID를 path변수로 활용하여 해당 상품의 정보를 조회합니다.

=== 요청
operation::product-soloGet[snippets='path-parameters,request-body']
=== 응답
operation::product-soloGet[snippets='response-fields,response-body']
=== 예제
operation::product-soloGet[snippets='http-request,http-response']

== 상품 목록 조회
=== 기본정보
|===
|Method | URL |Authentication method

|GET
|/api/products
|NONE
|===
**설명**: 모든 상품 목록을 페이지네이션 형태로 조회합니다. 각 상품의 ID, 이름, 가격, 이미지 URL, 카테고리 이름 등을 포함합니다.

=== 요청
operation::product-get[snippets='request-body']
=== 응답
operation::product-get[snippets='response-fields,response-body']
=== 예제
operation::product-get[snippets='http-request,http-response']



== 상품 옵션 조회
=== 기본정보
|===
|Method | URL |Authentication method

|GET
|/api/products/{productId}/options
|NONE
|===
**설명**: 특정 상품의 옵션 목록을 조회합니다. 각 옵션의 ID, 이름, 수량 등을 반환합니다.

=== 요청
operation::product-option-get[snippets='path-parameters']
=== 응답
operation::product-option-get[snippets='response-fields,response-body']
=== 예제
operation::product-option-get[snippets='http-request,http-response']



== 카테고리 조회
=== 기본정보
|===
|Method | URL |Authentication method

|GET
|/api/categories
|NONE
|===
**설명**: 모든 카테고리 목록을 조회합니다. 각 카테고리의 ID, 이름, 색깔, 이미지 URL, 설명 등을 반환합니다.

=== 요청
operation::category-get[snippets='request-body']
=== 응답
operation::category-get[snippets='response-fields,response-body']
=== 예제
operation::category-get[snippets='http-request,http-response']



== 위시 추가
=== 기본정보
|===
|Method | URL |Authentication method

|POST
|/api/wishes
|AccessToken
|===
**설명**: 특정 상품을 위시리스트에 추가합니다. 상품의 ID와 수량을 제출합니다.

_**quantity는 필수 아닙니다 무시하시면 되요!**_

=== 요청
operation::wish-add[snippets='request-headers,request-fields,request-body']
=== 응답
operation::wish-add[snippets='response-body']
=== 예제
operation::wish-add[snippets='http-request,http-response']

== 위시 조회
=== 기본정보
|===
|Method | URL |Authentication method

|GET
|/api/wishes
|AccessToken
|===
**설명**: 사용자의 위시리스트를 조회합니다. 각 위시 항목의 상품 ID, 이름, 가격, 이미지 URL, 수량 등을 반환합니다.

=== 요청
operation::wish-get[snippets='request-headers,request-body']
=== 응답
operation::wish-get[snippets='response-fields,response-body']
=== 예제
operation::wish-get[snippets='http-request,http-response']


== 위시 삭제
=== 기본정보
|===
|Method | URL |Authentication method

|DELETE
|/api/wishes/{wishId}
|AccessToken
|===
**설명**: 위시리스트에서 특정 상품을 삭제합니다. 위시 ID를 URL 경로에 포함하여 요청합니다.

=== 요청
operation::wish-delete[snippets='request-headers,path-parameters']
=== 응답
operation::wish-delete[snippets='response-body']
=== 예제
operation::wish-delete[snippets='http-request,http-response']

== 상품 주문하기
=== 기본정보
|===
|Method | URL |Authentication method

|POST
|/api/orders
|AccessToken
|===
**설명**: 특정 상품의 옵션을 주문합니다. 옵션 ID, 수량, 배송 메시지를 포함합니다. 주문 번호, 주문된 옵션 ID, 수량, 주문 일시, 배송 메시지를 반환합니다.

=== 요청
operation::order-example[snippets='request-headers,request-fields,request-body']
=== 응답
operation::order-example[snippets='response-fields,response-body']
=== 예제
operation::order-example[snippets='http-request,http-response']

== 멤버 포인트 조회하기
=== 기본정보
|===
|Method | URL |Authentication method

|GET
|/api/points
|AccessToken
|===
**설명**: 멤버의 잔여 포인트를 조회합니다. 멤버 특정을 위해 로그인시 발급된 토큰이 필수로 요구됩니다.

=== 요청
operation::point-get[snippets='request-headers,request-body']
=== 응답
operation::point-get[snippets='response-fields,response-body']
=== 예제
operation::point-get[snippets='http-request,http-response']