### get option list
GET http://localhost:8080/api/options
Content-Type: application/json

### get option list by product id
GET http://localhost:8080/api/options/products/1
Content-Type: application/json

### get option
GET http://localhost:8080/api/options/1
Content-Type: application/json

### create option
POST http://localhost:8080/api/options
Content-Type: application/json

{
  "name": "123",
  "count": 1000,
  "productId": 1
}

### update option
PUT http://localhost:8080/api/options/1
Content-Type: application/json

{
  "name": "aaa",
  "count": 123,
  "productId": 1
}

### delete option
DELETE http://localhost:8080/api/options/1
Content-Type: application/json