DELETE
FROM options;
DELETE
FROM wishes;
DELETE
FROM products;
DELETE
FROM users;
DELETE
FROM categories;

ALTER TABLE products
    ALTER COLUMN id RESTART WITH 1;
ALTER TABLE options
    ALTER COLUMN id RESTART WITH 1;
ALTER TABLE wishes
    ALTER COLUMN id RESTART WITH 1;
ALTER TABLE categories
    ALTER COLUMN id RESTART WITH 1;
ALTER TABLE users
    ALTER COLUMN id RESTART WITH 1;
